### Create Order
POST http://localhost:8080/api/v1/orders
Content-Type: application/json

{
  "userId": "u-1",
  "productId": "p-42",
  "amount": 1499.00
}


###
GET http://localhost:8080/api/v1/orders/5c0f961a-da11-4e79-8883-4b2bd23566ef

###

GET http://localhost:8083/health

