package com.orderservice.orderservice.order.domain.service;

import com.orderservice.orderservice.order.domain.model.OrderEntity;
import com.orderservice.orderservice.order.domain.repository.OrderRepository;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;

@Service
public class OrderService {

    private final OrderRepository repo;

    public OrderService(OrderRepository repo) {
        this.repo = repo;
    }

    public OrderEntity create(String userId, String productId, BigDecimal amount) {
        // same behavior as before: persist with status=PENDING (id generated by Hibernate)
        return repo.save(new OrderEntity(userId, productId, amount, "PENDING"));
    }
}